disabled_rules:
  - force_cast
  - force_try

opt_in_rules:
  - empty_count
  - fatal_error_message

line_length: 120
function_body_length:
  warning: 40
  error: 60

excluded:
  - Pods
  - Carthage
  - build
